x-environment: &shared-environment
  POSTGRES_USER: ${POSTGRES_USER:-explorer451}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-explorer451}
  POSTGRES_DB: ${POSTGRES_DB:-explorer451}
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - explorer451
    healthcheck:
      test: ["CMD", "awslocal", "s3", "ls"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      <<: *shared-environment
    ports:
      - "5432:5432"
    networks:
      - explorer451
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-explorer451} -d ${POSTGRES_DB:-explorer451}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-explorer451@explorer451.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-explorer451}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_LOGIN_REQUIRED: "False"
    volumes:
      - ./tmp/pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8081:80"
    networks:
      - explorer451
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  explorer451:
    driver: bridge
